<?php
/**
 * Created by PhpStorm.
 * User: korman
 * Date: 07.02.16
 * Time: 15:10.
 */
namespace ImageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
}
