image_album_index:
    path:     /
    defaults: { _controller: ImageBundle:Album:index }

image_ajax_album_list:
    path:     /ajax/list
    defaults: { _controller: ImageBundle:Album:ajaxList }
    options:
        expose: true

image_ajax_album_items_by_page:
    path:     /ajax/album/{id}/page/{page}
    defaults: { _controller: ImageBundle:Album:ajaxItems, page: 1 }
    options:
        expose: true

image_album_pagination:
    path:     /ajax/album/{id}/pagination/{page}
    defaults: { _controller: ImageBundle:Album:pagination }
    options:
        expose: true