image_album_index:
    path:     /
    defaults: { _controller: ImageBundle:Album:index }

image_album_list:
    path:     /album-list
    defaults: { _controller: ImageBundle:Album:albumList }
    options:
        expose: true

image_album_items_by_page:
    path:     /album/{id}/page/{page}
    defaults: { _controller: ImageBundle:Album:items, page: 1 }
    options:
        expose: true

image_album_pagination:
    path:     /album/{id}/pagination/{page}
    defaults: { _controller: ImageBundle:Album:pagination }
    options:
        expose: true